In [1]:
import numpy as np


In [2]:
def progressao_aritmetica(a1, r, n):
 ### Seu código inicia aqui ###  
    lista_pa = []	
    lista_pa.append(a1)
    for i in range(n-1):
        lista_pa.append(lista_pa[-1] + r)
  ### Seu código termina aqui ###
    return lista_pa

In [3]:
progressao_aritmetica(1, 2, 20)

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39]

In [4]:
def soma_pa(a1, r, n):
    soma = 0
    ### Seu código inicia aqui ###	
    lista_pa = []	
    lista_pa.append(a1)
    for i in range(n-1):
        lista_pa.append(lista_pa[-1] + r)
    soma= sum(lista_pa)
    ##print(lista_pa)
    ### Seu código termina aqui ###
    return soma

In [5]:
soma_pa(1, 2, 4)

16

In [6]:
def progressao_geometrica(a1, q, n):
    pg = []	
    ### Seu código inicia aqui ###
    pg.append(a1)
    for i in range(n-1):
        pg.append(pg[-1] * q)
    ### Seu código termina aqui ###
    return pg

In [7]:
progressao_geometrica (1, 2, 4)

[1, 2, 4, 8]

In [8]:
progressao_geometrica (1, 2, 3)

[1, 2, 4]

In [9]:
def soma_pg(a1, q, n):
    soma = 0
### Seu código inicia aqui ###	
    pg = []	
    pg.append(a1)
    for i in range(n-1):
     pg.append(pg[-1] * q)
    soma = sum(pg)
    ### Seu código termina aqui ###
    return soma

In [10]:
soma_pg(1, 2, 3)

7

In [11]:
soma_pg(1, 2, 4)

15

In [12]:
def fibonacci(n):
    fib = []
    ### Seu código inicia aqui ###
    fib = [0,1]
    if n==1:      
        fib =[0]
    elif n==2:
        fib = [0,1]
    else:
        while (len(fib)<n): # Enquanto o número de itens for menor que n
            fib.append(0)
        if (n==0 or n==1): # Se n for igual a zero ou 1, retorna 1 elemento
            return 1
        else:
            fib[0]= 0
            fib[1]= 1
            for i in range(2, n):
                fib[i]=fib[i-1]+fib[i-2]
    return fib
    ### Seu código termina aqui ###     

In [13]:
fibonacci(2)

[0, 1]

In [14]:
def soma_fibonacci(n):

    soma = 0
    ### Seu código inicia aqui ###	
    fib = [0,1]
    if n==1:      
        fib =[0]
    elif n==2:
        fib = [0,1]
    else:
        while (len(fib)<n): # Enquanto o número de itens for menor que n
            fib.append(0)
        if (n==0 or n==1): # Se n for igual a zero ou 1, retorna 1 elemento
            return 1
        else:
            fib[0]= 0
            fib[1]= 1
            for i in range(2, n):
                fib[i]=fib[i-1]+fib[i-2]
        soma = sum(fib)
    ### Seu código termina aqui ###
    return soma

In [15]:
soma_fibonacci(1)

0

In [16]:
def primo(n):
    resultado = False
    ### Seu código inicia aqui ###
    total= 0
    for i in range(1, n+1): 
        if n %i ==0:
         total += 1
    if total ==2:
          resultado = True
    else:
        resultado = False
    ### Seu código termina aqui ###
    return resultado

In [17]:
primo(8)

False

In [18]:
def fit_linear(x, y):
    A, B = 0, 0
    ### Seu código inicia aqui ###
    x = np.array(x)
    y = np.array(y)
    n = x.shape[0]
    B= (n*(x*y).sum()-x.sum()*y.sum())/(n*(x**2).sum()-(x.sum())**2)
    A= (y.sum()-B*x.sum())/n
    ### Seu código termina aqui ###
    return A, B

In [19]:
fit_linear([1, 2, 3, 4, 5], [1, 2, 3, 4, 5])

(0.0, 1.0)

In [20]:
fit_linear([1, 2, 3, 4, 5], [11, 21, 31, 41, 51])

(1.0, 10.0)

In [30]:
def numpy_seno(inicial, final, n_elementos):
    vetor = None
    ### Seu código inicia aqui ###
    import random
    #np.random.seed(0)
    n_random = np.linspace(inicial, final, num= n_elementos)
    #print (n_random)
    n_seno = np.sin(n_random)
    vetor = n_seno
    ### Seu código termina aqui ###
    return vetor

In [33]:
numpy_seno(0, 1, 11)

array([0.        , 0.09983342, 0.19866933, 0.29552021, 0.38941834,
       0.47942554, 0.56464247, 0.64421769, 0.71735609, 0.78332691,
       0.84147098])

In [34]:
numpy_seno(2, 3, 4)

array([0.90929743, 0.86320937, 0.8084964 , 0.74570521, 0.67546318,
       0.59847214, 0.51550137, 0.42737988, 0.33498815, 0.23924933,
       0.14112001])

In [23]:
def cria_ndarray(linhas, colunas, min, max):
    np.random.seed(137)
    matrix = None
    ### Seu código inicia aqui ###	
    m_random = np.random.uniform(low= min, high= max, size=(linhas, colunas))
    matrix = m_random
    ### Seu código termina aqui ###
    return matrix

In [24]:
cria_ndarray(2, 3, 1, 2)

array([[1.94385021, 1.08854403, 1.69537097],
       [1.69999035, 1.49960034, 1.50270302]])